name: semver

on: [workflow_dispatch]

jobs:
  release:
    name: Build
    runs-on: "ubuntu-18.04"
    steps:
    - uses: actions/checkout@v2
    - uses: olegsu/semver-action@v1
      id: version
      with:
        version_file: "./VERSION" # load version from this file instead of using explicit version
        bump: patch # [patch,minor,major] (patch is default)
    - name: Get the new version
      run: echo "${{ steps.version.outputs.version }}" # 0.1.3