name: semver

on: [workflow_dispatch]

jobs:
  release:
    name: Build
    runs-on: "ubuntu-18.04"
    steps:
    - uses: olegsu/semver-action@v1
      id: version
      with:
        version: "1.1.1" # required
        bump: patch # [patch,minor,major] (patch is default)
    - name: Get the new version
      run: echo "${{ steps.version.outputs.version }}" # 1.1.2